#!/usr/bin/env python
"""
Chuck this in : ~/bin/wineprefix

$ chmod +x ~/bin/wineprefix
$ wineprefix list
# makes a list of directories at ~/.local/share/wineprefixes
borderlands2
masseffect3
fonv

$ cd ~/Games/FalloutNewVegas/
$ wineprefix fonv ./FalloutNV.exe

$ wineprefix fonv remove
# removes ~/.local/share/wineprefixes/fonv/
"""

import sys
import os
import stat
import shutil
import subprocess

def remove_readonly(fn, path, excinfo):
    if fn is os.rmdir:
        os.chmod(path, stat.S_IWRITE)
        os.rmdir(path)
    elif fn is os.remove:
        os.chmod(path, stat.S_IWRITE)
        os.remove(path)

if __name__ == "__main__":
    wineprefix_path = os.path.expanduser("~/.local/share/wineprefixes")
    args = sys.argv[1:]

    if not len(args) > 0:
        print("Missing prefix")
        sys.exit()

    if args[0] == "list":
        for folder in os.listdir(wineprefix_path):
            print(folder)
    else:
        if len(args) < 2:
            print("no command")
            sys.exit()

        prefix = args[0]
        args = args[1:]

        if args[0] == "remove":
            shutil.rmtree(os.path.abspath(wineprefix_path + "/"
                                          + prefix), onerror=remove_readonly)

        elif args[0] == "winetricks":
            # setup the prefix
            wine_command = ['WINEPREFIX=' + wineprefix_path + "/" + prefix]  

            cmd = " ".join(wine_command + args)
            print(cmd)
            # os.popen(cmd)
            subprocess.Popen(cmd, shell=True)

        else:
            wine_command = [
                'WINEPREFIX=' + wineprefix_path + "/" + prefix,  # setup the prefix
                "wine"]                                          # then use wine

            cmd = " ".join(wine_command + args)
            print(cmd)
            # os.popen(cmd)
            subprocess.Popen(cmd, shell=True)
